module.exports = {
  AFFILIATE_DATABASE: 'affiliate',
  APPLICATION_SERVICE_PORT: 8080,
  APPLICATION_SERVICE_HOST: '0.0.0.0',
  MONGODB_SERVICE_HOST: '127.0.0.1',
  MONGODB_SERVICE_PORT: '27017',
  MONGODB_CONNECTION_DB: 'testdatabase',
  RETRY_COUNT: 0,
  MAILER_FROM_EMAIL: 'bquigley@tfd.ie'
};
